[package]
name = "mimallocator"
version = "0.1.0"
authors = ["Valery Piashchynski"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]

[features]
MI_ENCODE_FREELIST = []
MI_PADDING = []